# .project-metadata.yaml
name: AI Inference Scaling Optimization
description: A multi-objective optimization framework that enables to allocate inference tasks across models by balancing accuracy, cost, and latency.
author: Minseok Jung (Cloudera Inc.)
specification_version: 1.0
prototype_version: 1.0
date: "2025-10-21"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.11
    edition: Standard

tasks:
  - type: run_session
    name: Install dependencies
    script: 01_Installer/install.py
    short_summary: >-
      Install dependencies, set environment variables, and upload data
    cpu: 2
    memory: 8