# .project-metadata.yaml
name: AI Inference Scaling Optimization
description: A multi-objective optimization framework that enables to allocate inference tasks across models by balancing accuracy, cost, and latency.
author: Minseok Jung (Cloudera Inc.)
specification_version: 1.0
prototype_version: 1.0
date: "2025-10-21"

models:
  gpt5:
    name: "GPT-5"
    c_in: 0.00000125
    c_out: 0.00001
    t_in: 0.0005
    t_out: 0.005
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.94
    acc_std: 0.02
    default_parallel: 4
  gpt5-mini:
    name: "GPT-5 Mini"
    c_in: 0.00000025
    c_out: 0.000002
    t_in: 0.00025
    t_out: 0.002
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.92
    acc_std: 0.03
    default_parallel: 4
  gpt5-nano:
    name: "GPT-5 Nano"
    c_in: 0.00000005
    c_out: 0.0000004
    t_in: 0.0001
    t_out: 0.001
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.91
    acc_std: 0.04
    default_parallel: 4
  nvidia-nemotron-ultra-253b:
    name: "Nvidia Llama Nemotron Ultra 253B"
    c_in: 0.0000009
    c_out: 0.0000028
    t_in: 0.001
    t_out: 0.01
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.93
    acc_std: 0.05
    default_parallel: 4
  nvidia-nemotron-h-47b:
    name: "Nvidia Nemotron H 47B"
    c_in: 0.0000004
    c_out: 0.0000015
    t_in: 0.0004
    t_out: 0.004
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.92
    acc_std: 0.06
    default_parallel: 4
  nvidia-nemotron-nano-9b-v2:
    name: "Nvidia Nemotron Nano 9B v2"
    c_in: 0.0000002
    c_out: 0.000001
    t_in: 0.00012
    t_out: 0.0012
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.91
    acc_std: 0.07
    default_parallel: 4
  qwen3-max:
    name: "Qwen3-Max"
    c_in: 0.0000009
    c_out: 0.0000024
    t_in: 0.0008
    t_out: 0.008
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.90
    acc_std: 0.04
    default_parallel: 4
  qwen3-next-80b-a3b:
    name: "Qwen3-Next-80B-A3B"
    c_in: 0.0000005
    c_out: 0.00000125
    t_in: 0.0004
    t_out: 0.004
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.89
    acc_std: 0.05
    default_parallel: 4
  qwen3-30b-a3b:
    name: "Qwen3-30B-A3B"
    c_in: 0.00000035
    c_out: 0.0000009
    t_in: 0.00025
    t_out: 0.002
    mu_Lin: 1024
    sigma_Lin: 64
    mu_Lout: 2048
    sigma_Lout: 128
    acc_mean: 0.88
    acc_std: 0.06
    default_parallel: 4
